/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Hawinna
 */
public class kasir extends javax.swing.JFrame {
    ArrayList<String>Daftarpesanan=new ArrayList<>();
    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
        
         getContentPane().setBackground(new java.awt.Color(255, 192, 203)); // background utama (pink muda)

    jLabel4.setForeground(new java.awt.Color(255, 105, 180)); // judul pink lebih terang

    nomor_meja.setBackground(new java.awt.Color(255, 228, 225));
    nama_pemesan.setBackground(new java.awt.Color(255, 228, 225));

    pesanan.setBackground(new java.awt.Color(255, 182, 193));

    list_menu.setBackground(new java.awt.Color(255, 240, 245));

    // tombol
    hapus.setBackground(new java.awt.Color(255, 105, 180));
    tambah.setBackground(new java.awt.Color(255, 105, 180));
    proses.setBackground(new java.awt.Color(255, 20, 147));

    hapus.setForeground(java.awt.Color.WHITE);
    tambah.setForeground(java.awt.Color.WHITE);
    proses.setForeground(java.awt.Color.WHITE);

    // biar warna tombol muncul (kadang defaultnya tidak aktif)
    hapus.setFocusPainted(false);
    tambah.setFocusPainted(false);
    proses.setFocusPainted(false);

        pesanan.removeAllItems();
        pesanan.addItem("Makanan");
        pesanan.addItem("Minuman");
        pesanan.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomor_meja = new javax.swing.JTextField();
        nama_pemesan = new javax.swing.JTextField();
        pesanan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomor_meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_mejaActionPerformed(evt);
            }
        });

        nama_pemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pemesanActionPerformed(evt);
            }
        });

        pesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananActionPerformed(evt);
            }
        });

        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_menu);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("No. Meja:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Menu:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("APLIKASI PEMESANAN MAKANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tambah))
                                    .addComponent(jLabel4))
                                .addGap(0, 73, Short.MAX_VALUE))
                            .addComponent(nomor_meja)
                            .addComponent(nama_pemesan)
                            .addComponent(pesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(proses)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomor_meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(proses)
                        .addContainerGap())
                    .addComponent(tambah)
                    .addComponent(hapus)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_pemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pemesanActionPerformed

    private void pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananActionPerformed
        if (pesanan.getSelectedItem() == null) {
                return; // hentikan kalau kosong
    }

        String kategori = pesanan.getSelectedItem().toString();
        if (kategori.equals("Makanan")) {
        list_menu.setListData(new String[]{
            "Nasi Goreng",
            "Mie Ayam",
            "Sate",
            "Bakso"
        });
        } else if (kategori.equals("Minuman")) {
        list_menu.setListData(new String[]{
            "Es Teh",
            "Jus",
            "Kopi",
            "Air Mineral"
        });
    }
    }//GEN-LAST:event_pesananActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
       String nomorMeja=nomor_meja.getText();
       String namaPemesan=nama_pemesan.getText();

       if(Daftarpesanan.isEmpty()){
    JOptionPane.showMessageDialog(this, "Belum ada pesanan!");
    return;
}

    String hasil = "";

    for(String p : Daftarpesanan){
    hasil += p + "\n";
}

JOptionPane.showMessageDialog(this,
    "===== STRUK PESANAN =====\n" +
    "No Meja   : " + nomorMeja +
    "\nNama      : " + namaPemesan +
    "\n------------------------\n" +
    hasil +
    "------------------------"
);
       
    }//GEN-LAST:event_prosesActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String menu=list_menu.getSelectedValue();
        if(menu==null){
            JOptionPane.showMessageDialog(this,"Pilih menu dulu!");
            return;
        }
        String inputJumlah=JOptionPane.showInputDialog("Masukkan jumlah: ");
        int jumlah=Integer.parseInt(inputJumlah);
        Daftarpesanan.add(menu+"("+jumlah+"porsi)");
        JOptionPane.showMessageDialog(this,"Ditambahkan");
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
     int konfirmasi = JOptionPane.showConfirmDialog(
    this,
    "Yakin hapus semua pesanan?",
    "Konfirmasi",
    JOptionPane.YES_NO_OPTION
);

if(konfirmasi == JOptionPane.YES_OPTION){
    Daftarpesanan.clear();

    JOptionPane.showMessageDialog(this, "Semua pesanan dihapus!");

    nomor_meja.setText("");
    nama_pemesan.setText("");
    list_menu.clearSelection();
}
    }//GEN-LAST:event_hapusActionPerformed

    private void nomor_mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_mejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_mejaActionPerformed

    /**
     * @param args the command line arguments
       public static void main(String args[]) {
  */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField nama_pemesan;
    private javax.swing.JTextField nomor_meja;
    private javax.swing.JComboBox<String> pesanan;
    private javax.swing.JButton proses;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
